config/routes.rb
Rails.application.routes.draw do

  root to: 'tasks#index'

  resources :tasks

  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
      can :create, Task
      can :manage, Task do |task|
        task.user == user
      end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :sub_tasks, class_name: "Task",
                          foreign_key: "parent_id"
 
  belongs_to :parent, class_name: "Task"

  validates_presence_of :name, :duration, :user_id

  searchable do
    text :name
    integer :duration
  end

  scope :recent, -> { order(updated_at: :desc) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  require 'will_paginate/array'
  load_and_authorize_resource

  before_action :authenticate_user!
  before_action :get_recent

  respond_to :js
  
  def index
    @search = Sunspot.search(Task) {
      fulltext params[:search_name]
      all_of do
        with(:duration).less_than(params[:search_less]) if !params[:search_less].blank?
        with(:duration).greater_than(params[:search_more]) if !params[:search_more].blank?
      end
    } 
    @tasks = @search.results
    @tasks = @tasks.paginate(:page => params[:page], per_page: 10)
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.user_id ||= current_user.id

    redirect_to :back if !@task.save
  end

  def update
    redirect_to :back if !@task.update(task_params)
  end

  def destroy
    @task.destroy
  end

  private
    def get_recent
      @tasks = Task.recent.paginate(:page => params[:page], per_page: 10)
    end

    def task_params
      params.require(:task).permit(:name, :duration, :user_id, :search_name, :search_less,
        :search_more)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TestApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"}
    =javascript_include_tag "jquery.turbolinks"
    %script{:src => "//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.metro
    .page
      .container
        #content
          #notice
            =notice
          = yield
      = render 'shared/footer'

app/views/shared/_footer.html.haml
#footer_true.navbar
  .navbar-content.ribbed-blue.fg-white
    %item &copy; Test App ;-) 2015
    %item
      %span
        - if current_user.present?
          Приветствуем,
          =current_user.try(:email)
          = link_to " Выйти", destroy_user_session_path, method: :delete
        - else
          = link_to "  Вход", new_user_session_path

app/views/tasks/_form.html.haml
= simple_form_for @task, remote: true do |f|
  = f.error_notification

  .form-inputs.input-control.text.size3
    = f.input :name
    = f.input :duration
    %br
  .form-actions
    = f.button :submit, class: 'button primary'

app/views/tasks/_index.html.haml
%h1 Listing tasks
%p
  = form_tag tasks_path, :method => :get do
    .input-control.text.size3
      Search by name:
      = text_field_tag :search_name, params[:search_name]
    .input-control.text.size2
      With duration less than:
      = text_field_tag :search_less, params[:search_less]
    .input-control.text.size3
      With duration more than:
      = text_field_tag :search_more, params[:search_more]
    = submit_tag "Search", :name => nil, class: 'button primary'

%table.table.hovered
  %thead
    %tr
      %th Name
      %th Duration
      %th User
      %th
      %th
      %th
      
  %tbody
    - @tasks.each do |task|
      %tr
        %td
          =link_to task, remote: true do
            = task.name
        %td= task.duration
        %td= task.user.email
        %td= link_to 'Edit', edit_task_path(task), class: 'button primary small', remote: true
        %td= link_to 'Destroy', task, :method => :delete, class: 'button danger small', :data => { :confirm => 'Are you sure?' }, remote: true

%br
= will_paginate @tasks
= link_to 'New Task', new_task_path, class: 'button primary', remote: true

app/views/tasks/_refresh.js.haml
$('#content').html("#{j (render 'index')}");
$.Notify.show("Success!!!");

app/views/tasks/_show.html.haml
%p#notice= notice

%h3
  = @task.name
%p
  %b Duration:
  = @task.duration
%p
  %b User:
  = @task.user.email

       
= link_to 'Edit', edit_task_path(@task), class: 'button primary'
= link_to 'Add SubTask', new_task_path(@task), class: 'button primary', remote: true
%br

app/views/tasks/create.js.haml
=render 'refresh'

app/views/tasks/destroy.js.haml
=render 'refresh'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/edit.js.haml
$.Dialog({shadow: true, overlay: true, title: "#{j (@task.name) + ' - Редактирование'}", padding: 36, content: "#{j (render 'form')}"});

app/views/tasks/index.html.haml
= render 'index'

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/new.js.haml
$.Dialog({shadow: true, overlay: true, title: "New task", padding: 36, content: "#{j (render 'form')}"});

app/views/tasks/show.html.haml
=render 'show'

app/views/tasks/show.js.haml
$.Dialog({shadow: true, overlay: true, title: "Task: #{@task.name}", padding: 36, content: "#{j (render 'show')}"});

app/views/tasks/update.js.haml
=render 'refresh'